spring.application.name=github-analysis-service

server.port=8082

spring.profiles.active=local

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

resilience4j.circuitbreaker.instances.githubApi.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.githubApi.slidingWindowSize=5
resilience4j.circuitbreaker.instances.githubApi.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.githubApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.githubApi.waitDurationInOpenState=30s
resilience4j.retry.instances.githubApi.maxAttempts=3
resilience4j.retry.instances.githubApi.waitDuration=2s
management.health.circuitbreakers.enabled=true
