spring.application.name=github-analysis-service

server.port=8082

spring.profiles.active=local

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}