spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - PreserveHostHeader

            - id: github-analysis-service
              uri: lb://github-analysis-service
              predicates:
                - Path=/github/**
              filters:
                - PreserveHostHeader