spring.application.name=api-gateway

server.port=8080

jwt.secret=yourVeryStrongSecretKeyForJwtAuthentication123456
jwt.expiration=86400000

spring.profiles.active=local

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}