server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - PreserveHostHeader

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


  instance:
    hostname: localhost


    prefer-ip-address: true