server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - PreserveHostHeader

            - id: github-analysis-service
              uri: lb://GITHUB-ANALYSIS-SERVICE
              predicates:
                - Path=/github/**
              filters:
                - PreserveHostHeader

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


  instance:
#    hostname: localhost


    prefer-ip-address: true